version: '3'
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - ./database:/data/db
    expose:
      - 27017
  buying-zone:
    container_name: bz
    restart: always
    image: bikeshaman/buying-zone:1.0.0
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    links:
      - mongo
